BEGIN;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS personal_budget_enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS family_budget_enabled BOOLEAN NOT NULL DEFAULT TRUE;

COMMIT;
